spring:
  application:
    name: forum
  datasource:
    url: jdbc:postgresql://localhost:5445/forum
    username: forum
    password: forum
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
